### ISSUE TITLE
Target .NET Standard 2.0

### ISSUE THREAD

**Issue by GerardSmit** [endlesstravel/Rockyfi#3]
Is it possible for Rockfyi to add a target for .NET Standard 2.0?
I'm using Rockfyi in a project but because the project doesn't target .NET Standard, I get the following warning:

![image](https://user-images.githubusercontent.com/2109929/67718686-8caa5e00-f9d0-11e9-815f-07082ff38932.png)

```
warning NU1701: Package 'Rockyfi 0.1.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

It only gives a warning, other than that everything works fine. Thanks for making this library 😊.

**Comment by endlesstravel** [comment]
thank for you like it. 😄 
I add .netstartard 1.0 declare in version 0.1.2 at https://www.nuget.org/packages/Rockyfi/0.1.2

**Comment by GerardSmit** [comment]
Thanks 😄
